version: '3.8'

services:
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    depends_on:
      - db
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5001
    depends_on:
      - api
  db:
    container_name: db
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
